// app/legal/terms/page.tsx
import type { Metadata } from "next";

type Section = { heading: string; content: string[] };

const sections: Section[] = [
  {
    heading: "Preface & Acceptance",
    content: [
      "This electronic record is issued under the Information Technology Act, 2000 and applicable amendments. It is generated by a computer system and does not require physical or digital signatures.",
      "Published pursuant to Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 to disclose rules, privacy policy, and terms of use for the Traferr application.",
      "By using the Traferr application on Google Play or the Apple iOS App Store, you agree to these Terms of Use, the End-User License Agreement, Privacy Policy, and Disclaimer. If you do not agree, do not use the application.",
    ],
  },
  {
    heading: "Definitions",
    content: [
      "“Application” means the Traferr mobile application including software, algorithms, and third-party software.",
      "“Company,” “we,” or “us” means Novazrehh Tech Solutions Private Limited, Behram Baug, Jogeshwari West, Mumbai – 400102.",
      "“You” means the user, including Traveler(s), Localite(s), customer, or viewer of the Application.",
      "“Services” means the Application, travel guidance, advice, information, software programs, documentation, data, databases, and other proprietary materials of the Company or its licensors.",
      "“Localite” means a user who volunteers to virtually or physically guide Traveler(s) within a Territory in accordance with these Terms.",
      "“Traveler(s)” means a user who engages Localites via the Application.",
      "“Territory” means the travel location for which the Traveler(s) has engaged the Localite(s).",
    ],
  },
  {
    heading: "1. Alterations to the Terms of Use",
    content: [
      "We may change these Terms at any time without notice. The most current version may be reviewed via our website.",
      "You are responsible for checking updates periodically. Continued use after changes signifies acceptance.",
    ],
  },
  {
    heading: "2. Right to Change Services",
    content: ["We may discontinue or change any service or feature on the Application at any time without notice."],
  },
  {
    heading: "3. Your Responsibilities / Liabilities",
    content: [
      "Use the Application only for lawful purposes. Do not upload or transmit content that infringes rights; is unlawful, threatening, abusive, harassing, defamatory, libellous, deceptive, fraudulent, invasive of privacy, or sexually explicit; victimizes or intimidates any person or group; impersonates others; contains viruses or malicious code; encourages criminal conduct; violates these Terms or posted guidelines; or interferes with others’ use.",
      "Do not damage, disable, overburden, or impair servers or networks, or interfere with others’ enjoyment of the Application.",
      "Do not attempt unauthorized access to Services, accounts, systems, or networks via hacking, password mining, or other means. We may take legal and technical measures to enforce this provision.",
    ],
  },
  {
    heading: "4. Spam",
    content: [
      "Do not use the Application or our tools to send unsolicited bulk communications or harvest user information for that purpose.",
      "We may terminate access and take legal or technical measures to prevent unsolicited bulk communications.",
    ],
  },
  {
    heading: "5. Proprietary Rights",
    content: [
      "We, our suppliers, and lawful users own rights in content posted on the Application. Content is protected by copyright, trademark, patent, trade secret laws, and international treaties.",
      "The Application’s design, layout, look, appearance, and graphics are owned or licensed by us; reproduction is prohibited.",
    ],
  },
  {
    heading: "6. License to Use & Account Rules",
    content: [
      "Unless otherwise stated, the Company and/or its licensors own IP in the Application and its materials. You may view, cache, and print pages for personal use, subject to these Terms.",
      "Account access is limited to the registered user. Before purchasing, you must confirm you are the registered user, are at least 18, and are truthfully providing government-issued ID for verification. Failure may result in forfeiture of winnings.",
      "Prohibited: republishing materials; selling, renting, or sublicensing; public display; reproducing or exploiting materials commercially; redistributing except where expressly allowed (and then only within your organization).",
      "Provide accurate, complete registration information and keep it updated.",
      "Maintain confidentiality of login credentials and do not allow others to use your account. You are responsible for all activity under your account, including unauthorized use. Defaulting users may be permanently blocked without refund.",
      "Requirements: a supported Android/iOS/Windows device with adequate connectivity; you bear all data charges.",
      "Promotions may carry additional rules (age, purchase amount, geography). You are responsible for compliance.",
      "We store and process information (including sensitive personal/health/financial data, if any) with reasonable security measures under the IT Act, 2000 and Rules. See our Privacy Policy at https://www.traferr.com. If you object, do not use the Application. Any sensitive data exchanged directly between Localites and Travelers is the disclosing party’s sole responsibility.",
      "Complaints: If more than 3 complaints are received against a Localite, action may be taken at the Company’s discretion. Gender fraud triggers immediate suspension. Defaulting Localites/Travelers may be tutored, failing which services may be terminated.",
    ],
  },
  {
    heading: "7. Transactions",
    content: [
      "Transactions effected and completed through the Application are governed by these Terms.",
      "We are a facilitator only and are not directly involved in user-to-user transactions beyond the Application. We do not post offers.",
      "We are not the owner of goods/services offered; we intervene in disputes only as specified; we are not responsible if offers are unsatisfactory.",
      "We do not guarantee completion of transactions. All parties remain subject to these Terms.",
      "Unless stated otherwise, all payments are in Indian Rupees. Travelers are responsible for all fees and applicable taxes as quoted at the app store download link.",
      "We are not responsible for losses due to authorization failures, bank limits, payment issues, or declines using third-party banking/money exchange services.",
      "We may cancel any request at our sole discretion (e.g., inability to fulfill, policy non-compliance). We will communicate cancellations and process any applicable refunds within a reasonable time.",
    ],
  },
  {
    heading: "8. Transaction Price & Subscriptions",
    content: [
      "Subscription fees provide access to services per the chosen plan term and renew automatically per initial plan settings. You may cancel per the policy below.",
      "Billing disputes must be raised within 7 days of the bill. Refunds, if any, are case-by-case at the Company’s sole discretion.",
    ],
  },
  {
    heading: "9. Localite Terms",
    content: [
      "The Application is a virtual marketplace for Localite goods/services.",
      "Localite payout: within 30 days of a successful, paid transaction, at mutually agreed pricing.",
      "Taxes: each party bears applicable taxes.",
      "Reverse shipping/overheads directly related to Localite services are borne by the Localite.",
      "Default in fulfilling requests may incur an 18% charge on total invoice value.",
      "Payments follow mutually agreed written terms.",
      "Localite warrants rights to use the name under which they are identified and registered and will comply with applicable laws.",
      "Localite will cooperate to provide offer details (description, price, images, limits) and promotional materials for exhibitions with 15 days’ notice; selection of promotional materials is at the Company’s discretion unless agreed in writing.",
      "Localite warrants offers meet industry standards and do not infringe IP or third-party rights; will maintain brand reputation and goodwill.",
      "Localite is solely responsible for its content and services and permits Company to use such content until termination/expiration of these Terms.",
      "Localite performance will not conflict with other agreements; Localite will not use the Application for fraud or to interfere with services.",
      "Non-solicitation: Localite will not directly/indirectly contact or communicate with Application Travelers for 2 years from termination of association with the Application/Company.",
      "Localite will provide required documents/information, warranting truthfulness; maintain confidentiality; indemnify the Company for defaults, breaches, or fraud.",
      "Localite will promote the Application by displaying Company-provided posters or as otherwise required.",
    ],
  },
  {
    heading: "10. Security Rules",
    content: [
      "Prohibited: unauthorized data access; probing/scanning/testing vulnerabilities; breaching authentication; interfering with service (virus, overload, flooding, spamming, mail bombing, crashing); sending unsolicited emails; forging headers. Violations may lead to civil/criminal liability. We may investigate and cooperate with law enforcement.",
      "The Application is intended for parties able to make binding contracts.",
      "You must comply with all applicable laws and pay statutory fees/taxes associated with activities on the Application.",
    ],
  },
  {
    heading: "11. Refunds / Cancellation / Credit Policy",
    content: [
      "All Localite Pack purchases are final; no refunds, returns, or exchanges.",
      "Complaints may be reviewed at the Company’s sole discretion; this does not obligate refunds or compensation.",
      "We may cancel purchase requests at our sole discretion (e.g., inability to meet requirements, policy non-compliance). We will communicate cancellations in appropriate time.",
      "Refunds, if any, are solely at the Company’s discretion, handled case-by-case. Travelers waive any claim to dispute/demand refunds through other means.",
      "If a refund is approved, processing is initiated within 5–7 working days from approval; credit to the original payment method or bank account typically within the same 5–7 working days, subject to bank/processor timelines.",
    ],
  },
  {
    heading: "12. Monitoring",
    content: ["We are not liable for content provided by others. We may refuse to post, edit, or remove content at our discretion; we are not responsible for any failure or delay in removal."],
  },
  {
    heading: "13. Copyright Infringement Claims",
    content: ["We respect IP rights. If you believe your work is copied and accessible on the Application in a way that constitutes infringement, contact us to report it."],
  },
  {
    heading: "14. Hyperlinks",
    content: [
      "The Application may include links to third-party websites (including automated results). Some may contain objectionable or inaccurate materials. Links do not imply endorsement.",
      "We are not responsible or liable for content or materials on third-party sites. Dealings with advertisers are solely between you and the advertiser.",
      "Do not create links to the Application without prior written consent from the Company.",
    ],
  },
  {
    heading: "15. Disclaimer of Warranties",
    content: [
      "The Application is provided “as is” and “as available.” To the extent permitted by law, we and our suppliers/affiliates disclaim implied warranties of merchantability, satisfactory quality, accuracy, timeliness, fitness for a particular purpose, and non-infringement.",
      "We do not warrant continuous availability of the Application or that information is complete, true, accurate, or non-misleading.",
      "Nothing on the Application constitutes advice of any kind.",
    ],
  },
  {
    heading: "16. Limitation of Liability",
    content: [
      "Your sole remedy is to discontinue use of the Application. Our total liability for claims related to use of the Application is limited to charges/fees, if any, paid by you to the Company for a specific service.",
      "We, our affiliates, and suppliers are not liable for any direct, indirect, special, incidental, consequential, or exemplary damages (including loss of profits, goodwill, data) arising from or in connection with the Application, Services, payment gateway services, or inability to use or reliance upon the Application.",
      "We make no guarantees about accuracy, reliability, completeness, or timeliness of content, or error-free/ uninterrupted operation. We assume no liability for delay, failure, interruption, or corruption of data transmitted in connection with use.",
    ],
  },
  {
    heading: "17. Indemnification",
    content: [
      "You agree to defend, indemnify, and hold harmless the Company, affiliates, employees, contractors, officers, directors, and agents from all liabilities, claims, demands, expenses (including attorney’s fees), and penalties arising from your use/misuse of the Application or breach of these Terms or applicable laws.",
    ],
  },
  {
    heading: "18. International Use",
    content: [
      "We make no representation that content is appropriate or available outside India. Accessing from territories where content is illegal is prohibited. If you access from outside India, you do so at your initiative and must comply with local laws.",
    ],
  },
  {
    heading: "19. Breach of Terms",
    content: [
      "If you breach these Terms, we may take appropriate action including suspending access, prohibiting access, blocking IPs, contacting your ISP, and/or initiating legal proceedings.",
      "Unauthorized use may give rise to claims for damages and/or constitute a criminal offense.",
    ],
  },
  {
    heading: "20. Severability & Entire Agreement",
    content: [
      "These Terms and any supplemental terms, policies, rules, and guidelines posted on the Application constitute the entire agreement and supersede prior agreements.",
      "If any provision is held invalid, the remainder remains in full force and effect, reflecting the parties’ original intent as closely as possible under applicable law.",
    ],
  },
  {
    heading: "21. Termination",
    content: [
      "Your right to use the Application terminates automatically if you violate these Terms. We may also terminate access, in whole or in part, at our sole discretion, with or without notice.",
    ],
  },
  {
    heading: "22. Governing Law & Jurisdiction",
    content: [
      "These Terms and related claims are governed by the laws of India. Courts in Mumbai have exclusive jurisdiction.",
      "We may seek injunctive or other equitable relief from any court of competent jurisdiction.",
    ],
  },
  {
    heading: "23. Miscellaneous & Age Confirmation",
    content: [
      "No waiver of any term shall be deemed a further or continuing waiver. Except as expressly provided in additional notices/licenses, these Terms govern your use of the Application.",
      "Changes to these Terms may only be made by revised posting on this page.",
      "You confirm that you are above 18 years of age and may use the Application only under this consent.",
      "If you do not agree to these Terms, cease using the Application immediately. To delete your account, use the contact instructions provided in the Application.",
    ],
  },
];

export const metadata: Metadata = {
  title: "Terms of Use — Traferr",
  description:
    "The terms governing access to and use of the Traferr application by Novazrehh Tech Solutions Private Limited.",
};

export default function TermsPage() {
  return (
    <div className="px-4 py-20">
      <div className="mx-auto w-full max-w-3xl space-y-10 rounded-3xl border border-slate-200 bg-white/95 p-10 shadow-xl shadow-slate-200/60">
        <header className="space-y-3">
          <p className="text-sm font-semibold uppercase tracking-wide text-sky-600">Terms</p>
          <h1 className="text-3xl font-semibold text-slate-900">Traferr Terms of Use</h1>
          <p className="text-sm text-slate-500">Effective January 1, 2025</p>
          <p className="text-base text-slate-600">
            Please review these Terms carefully. By using the Traferr application, you agree to be legally bound by them.
          </p>
        </header>
        <div className="space-y-8">
          {sections.map((section) => (
            <section key={section.heading} className="space-y-3">
              <h2 className="text-xl font-semibold text-slate-900">{section.heading}</h2>
              {section.content.map((paragraph, i) => (
                <p key={i} className="text-sm text-slate-600">
                  {paragraph}
                </p>
              ))}
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
